#!/bin/bash

# =============================================================================
# Setup Whitelabel Theme (Phase 124)
# Dynamic Branding & Multi-Tenant Support
# =============================================================================

echo "Setting up Whitelabel Theme..."
echo "================================================="
echo ""

echo "✓ Database Schema: whitelabel_schema.sql"
echo "✓ Theme Provider: src/providers/ThemeProvider.tsx"
echo ""

echo "================================================="
echo "Whitelabel Theme Setup Complete!"
echo ""
echo "Deployment Steps:"
echo ""
echo "1. **Run SQL Schema**:"
echo "   - Open Supabase SQL Editor"
echo "   - Execute: whitelabel_schema.sql"
echo "   - Verify tenants table created"
echo ""
echo "2. **Update Tailwind Config**:"
echo "   - Edit: tailwind.config.ts (or .mjs)"
echo "   - Replace hardcoded colors with CSS variables"
echo "   - Example:"
echo "   ```typescript"
echo "   colors: {"
echo "       primary: {"
echo "           500: 'var(--color-primary-500)',"
echo "           600: 'var(--color-primary-600)',"
echo "       }"
echo "   }"
echo "   ```"
echo ""
echo "3. **Wrap App with ThemeProvider**:"
echo "   - Edit: src/app/layout.tsx"
echo "   - Add:"
echo "   ```tsx"
echo "   import { ThemeProvider } from '@/providers/ThemeProvider';"
echo ""
echo "   export default function RootLayout({ children }) {"
echo "       const tenantSlug = getTenantSlug(); // From URL or domain"
echo "       return ("
echo "           <ThemeProvider tenantSlug={tenantSlug}>"
echo "               {children}"
echo "           </ThemeProvider>"
echo "       );"
echo "   }"
echo "   ```"
echo ""
echo "4. **Update Global CSS**:"
echo "   - Edit: app/globals.css"
echo "   - Add CSS variable defaults:"
echo "   ```css"
echo "   :root {"
echo "       --color-primary-500: #0066CC;"
echo "       --color-primary-600: #0052a3;"
echo "   }"
echo "   ```"
echo ""
echo "5. **Test Multi-Tenant Themes**:"
echo "   - Visit: /?tenant=logistik-a (Red theme)"
echo "   - Visit: /?tenant=logistik-b (Green theme)"
echo "   - Visit: /?tenant=cargo-express (Purple theme)"
echo ""
echo "Features Enabled:"
echo "  ✓ Dynamic brand colors per tenant"
echo "  ✓ Auto-generated color shades"
echo "  ✓ Custom logo support"
echo "  ✓ Font family customization"
echo "  ✓ RLS-protected tenant configs"
echo "  ✓ Fallback to default theme"
