#!/bin/bash

# =============================================================================
# Setup API Metering (Phase 119)
# Monetization Engine & Atomic Billing
# =============================================================================

echo "Setting up API Metering..."
echo "================================================="
echo ""

echo "✓ Database Schema: api_metering_schema.sql"
echo "✓ Metering Logic: src/lib/api-metering.ts"
echo ""

echo "================================================="
echo "API Metering Setup Complete!"
echo ""
echo "Deployment Steps:"
echo ""
echo "1. **Run SQL Schema**:"
echo "   - Open Supabase SQL Editor"
echo "   - Execute: api_metering_schema.sql"
echo "   - Verify tables created"
echo ""
echo "2. **Update Middleware** (src/middleware.ts):"
echo "   Add metering for API routes:"
echo ""
echo "   import { handleMeteredRequest, shouldMeterRequest } from '@/lib/api-metering';"
echo ""
echo "   export async function middleware(req: NextRequest) {"
echo "       // Meter API requests"
echo "       if (shouldMeterRequest(req.nextUrl.pathname)) {"
echo "           return handleMeteredRequest(req);"
echo "       }"
echo "       // ... other middleware"
echo "   }"
echo ""
echo "3. **Test Metering**:"
echo "   - Create API key in dashboard"
echo "   - Top up wallet (use topup_wallet function)"
echo "   - Make API request with key"
echo "   - Verify balance deducted"
echo ""
echo "Features:"
echo "  ✓ Atomic billing (no race conditions)"
echo "  ✓ Balance validation before request"
echo "  ✓ Usage logging for analytics"
echo "  ✓ Custom pricing per endpoint"
echo "  ✓ RLS-protected wallets and logs"
echo "  ✓ Insufficient balance detection (402 response)"
echo ""
echo "Pricing:"
echo "  • /api/v1/track: IDR 50 per request"
echo "  • /api/v1/cost: IDR 100 per request"
echo "  • /api/v1/webhook: IDR 25 per request"
echo "  • Others: IDR 50 per request"
echo ""
echo "SQL Functions Available:"
echo "  • meter_api_request() - Atomic billing"
echo "  • topup_wallet() - Add credits"
echo "  • view_api_usage_stats - Analytics view"
