#!/bin/bash

# =============================================================================
# Setup Custom Domains (Phase 125)
# Enterprise Branding & CNAME Support
# =============================================================================

echo "Setting up Custom Domains..."
echo "================================================="
echo ""

echo "✓ Domain Rewrite Logic: src/lib/domain-rewrite.ts"
echo "✓ Implementation Guide: CUSTOM_DOMAINS_GUIDE.md"
echo ""

echo "================================================="
echo "Custom Domains Setup Complete!"
echo ""
echo "Next Steps:"
echo ""
echo "1. **Read the Guide**:"
echo "   - Open: CUSTOM_DOMAINS_GUIDE.md"
echo "   - Review Vercel configuration options"
echo ""
echo "2. **Update Middleware**:"
echo "   - Edit: src/middleware.ts"
echo "   - Add handleDomainRewrite() call"
echo "   - Example:"
echo "   ```typescript"
echo "   import { handleDomainRewrite } from '@/lib/domain-rewrite';"
echo ""
echo "   export function middleware(req: NextRequest) {"
echo "       const rewrite = handleDomainRewrite(req);"
echo "       if (rewrite) return rewrite;"
echo "       // ... rest of middleware"
echo "   }"
echo "   ```"
echo ""
echo "3. **Create Tenant Routes**:"
echo "   - Create: app/tenant/[slug]/"
echo "   - Add layout.tsx and page.tsx"
echo "   - Implement tenant-specific branding"
echo ""
echo "4. **Configure Vercel**:"
echo "   - Add domains in Vercel Dashboard"
echo "   - Choose wildcard (*.domain) or individual domains"
echo ""
echo "5. **Optional: Edge Config**:"
echo "   - For production domain mapping"
echo "   - npm install @vercel/edge-config"
echo "   - Update getTenantSlug() function"
echo ""
echo "Features Enabled:"
echo "  ✓ Multi-tenant domain support"
echo "  ✓ Automatic domain rewriting"
echo "  ✓ Subdomain routing (client.cekkirim.com)"
echo "  ✓ Custom domain CNAME (portal.client.com)"
echo "  ✓ Tenant isolation"
echo "  ✓ Whitelabel branding ready"
