#!/bin/bash

# =============================================================================
# Setup Auto Poster (Phase 105)
# Social Media Distribution Automation
# =============================================================================

echo "Setting up Auto Poster..."
echo "================================================="
echo ""

# 1. Social Library
echo "1. Creating Library: src/lib/social-publisher.ts"

cat <<EOF > src/lib/social-publisher.ts
import { createClient } from '@/utils/supabase/server';

interface SocialResult {
    success: boolean;
    platform: 'twitter' | 'facebook';
    message?: string;
    postId?: string;
}

export async function postToTwitter(content: string, url: string): Promise<SocialResult> {
    const twitterKey = process.env.TWITTER_API_KEY;
    const twitterSecret = process.env.TWITTER_API_SECRET;
    
    // Check Config
    if (!twitterKey || !twitterSecret) {
        console.warn('Twitter credentials missing');
        return { success: false, platform: 'twitter', message: 'Credentials missing' };
    }

    try {
        // Pseudo-code for Twitter v2 API
        // const client = new TwitterApi({ appKey: ..., appSecret: ... });
        // const res = await client.v2.tweet(\`\${content} \${url}\`);
        
        // Mock success for now
        console.log(\`[Twitter] Posting: \${content} \${url}\`);
        return { success: true, platform: 'twitter', postId: 'mock_tweet_123' };
    } catch (e: any) {
        return { success: false, platform: 'twitter', message: e.message };
    }
}

export async function postToFacebook(content: string, url: string): Promise<SocialResult> {
    const fbToken = process.env.FB_PAGE_TOKEN;

    if (!fbToken) {
         console.warn('Facebook credentials missing');
         return { success: false, platform: 'facebook', message: 'Credentials missing' };
    }

    try {
        // Pseudo-code for Graph API
        // const res = await axios.post(\`https://graph.facebook.com/me/feed\`, { message: ..., link: ... });
        
        console.log(\`[Facebook] Posting: \${content} \${url}\`);
        return { success: true, platform: 'facebook', postId: 'mock_fb_123' };
    } catch (e: any) {
         return { success: false, platform: 'facebook', message: e.message };
    }
}

export async function logSocialActivity(articleTitle: string, results: SocialResult[]) {
    const supabase = await createClient();
    
    // Assuming table 'social_logs' exists or using raw JSON logging for now
    // Schema: id, article_title, platform, status, details, created_at
    
    const logs = results.map(r => ({
        article_title: articleTitle,
        platform: r.platform,
        status: r.success ? 'success' : 'failed',
        details: r.message || r.postId,
        created_at: new Date().toISOString()
    }));

    // Insert into DB (mocked table name)
    const { error } = await (supabase.from('social_logs') as any).insert(logs);
    
    if (error) console.error('Failed to log social activity:', error);
}
EOF
echo "   [✓] Social Library created."
echo ""

# 2. Webhook Route
echo "2. Creating Webhook: src/app/api/webhooks/auto-post/route.ts"
mkdir -p src/app/api/webhooks/auto-post

cat <<EOF > src/app/api/webhooks/auto-post/route.ts
import { NextResponse } from 'next/server';
import { postToTwitter, postToFacebook, logSocialActivity } from '@/lib/social-publisher';

export async function POST(request: Request) {
    // 1. Verify Secret (Basic security)
    const authHeader = request.headers.get('authorization');
    if (authHeader !== \`Bearer \${process.env.AUTO_POST_SECRET}\`) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // 2. Parse Payload
    const body = await request.json();
    const { title, url, excerpt } = body;

    if (!title || !url) {
        return NextResponse.json({ error: 'Missing title or url' }, { status: 400 });
    }

    console.log('[AutoPost] Triggered for:', title);

    // 3. Execute Posts (Parallel)
    const results = await Promise.all([
        postToTwitter(\`New Article: \${title}\n\n\${excerpt || ''}\`, url),
        postToFacebook(\`Check out our latest post: \${title}\`, url)
    ]);

    // 4. Log
    await logSocialActivity(title, results);

    return NextResponse.json({ 
        success: true, 
        results 
    });
}
EOF
echo "   [✓] Webhook Route created."
echo ""

# 3. DB Schema (Instruction)
echo "3. Creating SQL Schema (info only)..."

cat <<EOF > social_logs_schema.sql
create table public.social_logs (
  id bigint generated by default as identity primary key,
  article_title text not null,
  platform text not null,
  status text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
EOF
echo "   [✓] SQL Schema file created."
echo ""

echo "================================================="
echo "Setup Complete!"
echo "1. Create 'social_logs' table in Supabase."
echo "2. Set env vars: TWITTER_API_KEY, FB_PAGE_TOKEN, AUTO_POST_SECRET."
echo "3. Trigger POST /api/webhooks/auto-post with { title, url }."
