#!/bin/bash

# =============================================================================
# Setup AI Writer V2 (Phase 108)
# Database Integrated for Robust Content Management
# =============================================================================

echo "Setting up AI Writer V2 (Database Edition)..."
echo "================================================="
echo ""

# 1. Database Schema
echo "1. Generating SQL Schema..."
echo "   [!] Run this in Supabase SQL Editor:"

cat <<EOF > ai_writer_v2_schema.sql
-- Articles Table
CREATE TABLE public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text unique not null,
    content_md text, -- content in markdown
    meta_desc text,
    keywords text[],
    status text default 'draft', -- 'draft', 'published'
    thumbnail_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Policy (Allow all for internal use/admin)
CREATE POLICY "Enable all for authenticated users only" ON public.articles
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
EOF
echo "   [✓] ai_writer_v2_schema.sql created."
echo ""

# 2. AI Service
echo "2. Creating AI Service: src/lib/ai/writer.ts"
mkdir -p src/lib/ai

cat <<EOF > src/lib/ai/writer.ts
import OpenAI from 'openai';

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
    dangerouslyAllowBrowser: false, // Server side only
});

export async function generateArticleDB(topic: string, keywords: string[]) {
    if (!process.env.OPENAI_API_KEY) throw new Error("Missing OPENAI_API_KEY");

    const prompt = \`
    Write a comprehensive, SEO-optimized blog post about: "\${topic}".
    Target Audience: Indonesian e-commerce sellers and general users sending packages.
    Tone: Professional, Helpful, slightly casual.
    Language: Indonesian (Bahasa Indonesia).
    Keywords to include: \${keywords.join(', ')}.

    Format the output in Markdown.
    Structure:
    - H1 Title
    - Introduction
    - H2 Subheadings
    - Bullet points where appropriate
    - Conclusion featuring "CekKirim.com" as a solution.

    Do not include markdown code block fences (like \`\`\`markdown). Just return the raw markdown text.
    \`;

    const completion = await openai.chat.completions.create({
        messages: [
            { role: "system", content: "You are an expert Logistic SEO Content Writer." },
            { role: "user", content: prompt }
        ],
        model: "gpt-4o-mini", // Cost effective
        temperature: 0.7,
    });

    return completion.choices[0].message.content || "";
}
EOF
echo "   [✓] AI Service created."
echo ""

# 3. Server Actions
echo "3. Creating Actions: src/app/actions/articleActions.ts"

cat <<EOF > src/app/actions/articleActions.ts
'use server'

import { createClient } from '@/utils/supabase/server';
import { generateArticleDB } from '@/lib/ai/writer';
import { revalidatePath } from 'next/cache';

export async function createDraft(topic: string, keywords: string) {
    const supabase = await createClient();
    const keywordArray = keywords.split(',').map(k => k.trim());

    // 1. Generate Content
    const content = await generateArticleDB(topic, keywordArray);
    
    // 2. Derive Meta
    const titleMatch = content.match(/^# (.*$)/m);
    const title = titleMatch ? titleMatch[1] : topic;
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

    // 3. Insert DB
    const { data, error } = await supabase
        .from('articles')
        .insert({
            title,
            slug,
            content_md: content,
            keywords: keywordArray,
            status: 'draft'
        })
        .select()
        .single();
    
    if (error) console.error(error);
    revalidatePath('/dashboard/admin/blog/generator');
    return { success: !error, data };
}

export async function publishArticle(id: number) {
    const supabase = await createClient();
    
    // Update DB
    await supabase.from('articles').update({ status: 'published' }).eq('id', id);

    // Ideally, we would also write this to a persistent file (SSG) 
    // or just rely on ISR with the DB as the source of truth.
    // For now, we update status.
    revalidatePath('/dashboard/admin/blog/generator');
}
EOF
echo "   [✓] Server Actions created."
echo ""

# 4. Generator UI
echo "4. Creating Page: src/app/dashboard/admin/blog/generator/page.tsx"
mkdir -p src/app/dashboard/admin/blog/generator

cat <<EOF > src/app/dashboard/admin/blog/generator/page.tsx
'use client';

import { useState } from 'react';
import { createDraft, publishArticle } from '@/app/actions/articleActions';
import { Sparkles, Save, UploadCloud, Loader2 } from 'lucide-react';

export default function GeneratorPage() {
    const [topic, setTopic] = useState('');
    const [keywords, setKeywords] = useState('');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);

    const handleGenerate = async () => {
        setLoading(true);
        const res = await createDraft(topic, keywords);
        setLoading(false);
        if (res.success) {
            setResult(res.data);
            alert('Draft Created!');
        }
    };

    const handlePublish = async () => {
        if (!result) return;
        await publishArticle(result.id);
        alert('Published!');
    };

    return (
        <div className="p-8 max-w-4xl mx-auto">
            <h1 className="text-2xl font-bold mb-6 flex items-center gap-2">
                <Sparkles className="text-indigo-600" />
                AI Content Generator (Database)
            </h1>

            <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm mb-8">
                <div className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium mb-1">Topic</label>
                        <input 
                            className="w-full border rounded-lg p-2" 
                            value={topic} 
                            onChange={e => setTopic(e.target.value)}
                            placeholder="e.g. Tips Packing Kaca Pecah Belah"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium mb-1">Keywords</label>
                        <input 
                            className="w-full border rounded-lg p-2" 
                            value={keywords} 
                            onChange={e => setKeywords(e.target.value)}
                            placeholder="Comma separated"
                        />
                    </div>
                    <button 
                        onClick={handleGenerate}
                        disabled={loading || !topic}
                        className="bg-indigo-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50"
                    >
                        {loading && <Loader2 className="animate-spin w-4 h-4" />}
                        Generate Draft
                    </button>
                </div>
            </div>

            {/* Preview */}
            {result && (
                <div className="bg-gray-50 p-6 rounded-xl border">
                    <div className="flex justify-between items-center mb-4">
                        <h2 className="text-xl font-bold">{result.title}</h2>
                        <button 
                            onClick={handlePublish}
                            className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm flex items-center gap-2"
                        >
                            <UploadCloud className="w-4 h-4" />
                            Publish Live
                        </button>
                    </div>
                    <div className="prose max-w-none text-sm bg-white p-6 rounded border">
                        <pre className="whitespace-pre-wrap font-sans">{result.content_md}</pre>
                    </div>
                </div>
            )}
        </div>
    );
}
EOF
echo "   [✓] Generator UI created."
echo ""

echo "================================================="
echo "Setup Complete!"
echo "1. Run SQL in Supabase."
echo "2. Visit /dashboard/admin/blog/generator."
