create table public.social_logs (
  id bigint generated by default as identity primary key,
  article_title text not null,
  platform text not null,
  status text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
