-- Digital Store Schema
-- Phase: Passive Income

-- 1. Digital Products Table
CREATE TABLE IF NOT EXISTS public.digital_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    file_path TEXT NOT NULL, -- Path in Supabase Storage 'digital-assets' bucket
    product_type TEXT NOT NULL, -- TEMPLATE, EBOOK, SOFTWARE, COURSE, OTHER
    thumbnail_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. User Assets (Purchased Items)
CREATE TABLE IF NOT EXISTS public.user_assets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    product_id UUID REFERENCES public.digital_products(id) NOT NULL,
    purchase_trx_id UUID, -- Reference to wallet transaction or payment intent
    download_count INTEGER DEFAULT 0,
    max_downloads INTEGER DEFAULT 5, -- Security limit
    last_download_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast library lookup
CREATE INDEX IF NOT EXISTS idx_user_assets_owner ON public.user_assets(user_id);

-- 3. RLS
ALTER TABLE public.digital_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_assets ENABLE ROW LEVEL SECURITY;

-- Everyone can view active products (Storefront)
CREATE POLICY "Public view active products" ON public.digital_products FOR SELECT USING (is_active = true);

-- Users can view their own assets
CREATE POLICY "Users view own assets" ON public.user_assets FOR SELECT USING (auth.uid() = user_id);

-- 4. Storage Bucket Policy (Conceptual - needs manual setup in Supabase Dashboard)
-- Bucket: 'digital-assets'
-- Policy: SELECT only for authenticated users who OWN the asset (Checked via application logic + signed URLs usually)
-- For strict RLS on storage, we'd need a complex policy linking storage.objects to user_assets. 
-- For now, we rely on Signed URLs generated by server-side logic (Secure).
