-- ============================================
-- TITANIUM VAULT: BANK-GRADE FINANCIAL SECURITY
-- Idempotency, Atomic Transactions, Database Locks
-- ============================================
-- 1. STRICT IDEMPOTENCY CONSTRAINT
ALTER TABLE marketplace_orders
ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency ON marketplace_orders(idempotency_key)
WHERE idempotency_key IS NOT NULL;
-- 2. SALDO TIDAK BOLEH NEGATIF (Hard Constraint)
ALTER TABLE user_wallets
ADD CONSTRAINT IF NOT EXISTS balance_non_negative CHECK (balance >= 0);
-- 3. PERFORMANCE INDEXING
CREATE INDEX IF NOT EXISTS idx_orders_user_status ON marketplace_orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON marketplace_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_user ON user_wallets(user_id);
-- 4. SOFT DELETE (Never lose data)
ALTER TABLE users
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE marketplace_orders
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
-- 5. SYSTEM ERROR LOGGING (Blackbox Recorder)
CREATE TABLE IF NOT EXISTS system_error_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity TEXT CHECK (severity IN ('LOW', 'MEDIUM', 'CRITICAL')),
    error_message TEXT,
    stack_trace TEXT,
    context JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- 6. ATOMIC WITHDRAW FUNCTION (Titanium Vault Core)
CREATE OR REPLACE FUNCTION atomic_withdraw(
        p_user_id UUID,
        p_amount DECIMAL,
        p_idempotency_key TEXT,
        p_description TEXT
    ) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_current_balance DECIMAL;
v_new_transaction_id UUID;
BEGIN -- A. CHECK IDEMPOTENCY
IF EXISTS (
    SELECT 1
    FROM marketplace_orders
    WHERE idempotency_key = p_idempotency_key
) THEN RETURN jsonb_build_object(
    'status',
    'success',
    'message',
    'Transaction already processed',
    'code',
    200
);
END IF;
-- B. LOCK WALLET ROW (Pessimistic Locking)
SELECT balance INTO v_current_balance
FROM user_wallets
WHERE user_id = p_user_id FOR
UPDATE;
-- C. CHECK SUFFICIENT BALANCE
IF v_current_balance IS NULL THEN RAISE EXCEPTION 'Wallet not found';
END IF;
IF v_current_balance < p_amount THEN RAISE EXCEPTION 'Insufficient funds';
END IF;
-- D. EXECUTE DEDUCTION
UPDATE user_wallets
SET balance = balance - p_amount,
    updated_at = NOW()
WHERE user_id = p_user_id;
-- E. RECORD TRANSACTION
INSERT INTO marketplace_orders (user_id, total_amount, status, idempotency_key)
VALUES (
        p_user_id,
        p_amount,
        'PENDING',
        p_idempotency_key
    )
RETURNING id INTO v_new_transaction_id;
-- F. RETURN SUCCESS
RETURN jsonb_build_object(
    'status',
    'success',
    'tx_id',
    v_new_transaction_id,
    'code',
    200
);
EXCEPTION
WHEN unique_violation THEN RETURN jsonb_build_object(
    'status',
    'success',
    'message',
    'Transaction already processed (Race condition caught)',
    'code',
    200
);
WHEN check_violation THEN RETURN jsonb_build_object(
    'status',
    'error',
    'message',
    'Balance integrity violation',
    'code',
    400
);
WHEN OTHERS THEN RAISE;
END;
$$;
-- 7. RLS POLICIES (User cannot modify wallet directly)
ALTER TABLE user_wallets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own wallet" ON user_wallets;
CREATE POLICY "Users can view own wallet" ON user_wallets FOR
SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users cannot update wallet" ON user_wallets;
CREATE POLICY "Users cannot update wallet" ON user_wallets FOR
UPDATE USING (false);
-- Only backend can update
-- 8. IMMUTABLE TRANSACTIONS
DROP POLICY IF EXISTS "Transactions are immutable" ON marketplace_orders;
CREATE POLICY "Transactions are immutable" ON marketplace_orders FOR
UPDATE USING (false);
DROP POLICY IF EXISTS "Transactions cannot be deleted" ON marketplace_orders;
CREATE POLICY "Transactions cannot be deleted" ON marketplace_orders FOR DELETE USING (false);
COMMENT ON FUNCTION atomic_withdraw IS 'Titanium Vault: Atomic transaction with idempotency and row locking';
COMMENT ON TABLE system_error_logs IS 'Blackbox recorder for system errors';