-- =============================================================================
-- AI Writer V2 Schema
-- Articles table for database-integrated content management
-- =============================================================================

-- Articles Table
CREATE TABLE IF NOT EXISTS public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text unique not null,
    content_md text, -- content in markdown
    meta_desc text,
    keywords text[],
    status text default 'draft', -- 'draft', 'published'
    thumbnail_url text,
    author_id uuid references auth.users(id),
    category text,
    read_time_minutes int,
    views int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index on slug for fast lookups
CREATE INDEX IF NOT EXISTS articles_slug_idx ON public.articles(slug);

-- Create index on status for filtering
CREATE INDEX IF NOT EXISTS articles_status_idx ON public.articles(status);

-- Enable RLS
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Policy: Allow read for all (public articles)
CREATE POLICY "Allow public read for published articles" ON public.articles
    FOR SELECT
    USING (status = 'published');

-- Policy: Allow all for authenticated users (admin)
CREATE POLICY "Enable all for authenticated users" ON public.articles
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_articles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER articles_updated_at_trigger
    BEFORE UPDATE ON public.articles
    FOR EACH ROW
    EXECUTE FUNCTION update_articles_updated_at();
